### ISSUE TITLE
Upload to Github Releases fails

### ISSUE THREAD

**Issue by meeDamian** [lncm/docker-bitcoind#18]
Quite puzzlingly, the very same setup on `lncm/docker-lnd` works, but here, it doesn't 🤷🏻‍♂️.

`lncm/docker-lnd`: [This step](https://github.com/lncm/docker-lnd/blob/master/.github/workflows/on-tag.yml#L286-L294) results with [success](https://github.com/lncm/docker-lnd/runs/263977308#step:21:20).

```yml
      - name: Upload all artifact to Github Release
        uses: meeDamian/github-release@v1.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          prerelease: true
          gzip: false
          files: >
            docker-images/*
            binaries/*
```

`lncm/docker-bitcoind`: [This step](https://github.com/lncm/docker-bitcoind/blob/master/.github/workflows/on-tag.yml#L158-L163) results with [fail](https://github.com/lncm/docker-bitcoind/runs/295663562#step:19:1).

```yml
      - name: Upload images to Github Release
        uses: meeDamian/github-release@v1.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          gzip: false
          files: images/*
```
